config/routes.rb
Concensus::Application.routes.draw do
  resources :users
  resources :organizations
  resources :sessions
  resources :messages
  resources :channels
  resources :app

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => 'pages#index'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :channel, :founding_user_id

  has_one :channel, :dependent => :destroy
  has_many :organizations_users
  has_many :users, :through => :organizations_users

  after_create :create_channel

  def create_channel
    self.channel = Channel.find_or_create_by_name(self.name)
  end

  def founding_user
    user = User.find(self.founding_user_id)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    if current_user
      @organization = Organization.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @organization }
      end
    else
      flash[:error] = "Sign in to create an organization"
      respond_to do |format|
        format.html{redirect_to root_url}
      end
    end

  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= simple_form_for @organization, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.hidden_field :founding_user_id, :value => current_user.id

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), organizations_path, :class => 'btn'

app/views/organizations/edit.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/organizations/index.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.id, organization_path(organization)
        %td= organization.name
        %td=l organization.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_organization_path(organization), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), organization_path(organization), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
        -if current_user && current_user.founded_orgs.include?(@organization)
          .btn=link_to("create meeting", "/app")


= link_to t('.new', :default => t("helpers.links.new")), new_organization_path, :class => 'btn btn-primary'

app/views/organizations/new.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/organizations/show.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @organization.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), organizations_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_organization_path(@organization), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), organization_path(@organization), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  - if @organization.founding_user == current_user
    .btn= link_to("Create Meeting", "/app")