config/routes.rb
Concensus::Application.routes.draw do
  resources :users
  resources :organizations
  resources :sessions
  resources :messages
  resources :channels
  resources :app

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => 'pages#index'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Consensus"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Consensus
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", "/"
              %li= link_to "Organizations", "/organizations"
              %li= link_to "Users", "/users"

            #user_nav{:style => "float:right"}
              - if current_user
                Logged in as #{current_user.email}
                \#{link_to "Edit Account", edit_user_path(current_user)} or
                \#{link_to "Log out", log_out_path}
              - else
                = link_to "Sign up", sign_up_path
                or
                \#{link_to "log in", log_in_path}


    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            -if current_user
              -if !current_user.founded_orgs.empty?
                %h4 Founded Organizations:
                %ul.nav.nav-list
                  %li
                    - current_user.founded_orgs.each do |org|
                      %li= link_to "#{org.name}", organization_path(org)
              -if !current_user.organizations.empty?
                %h4 Member of:
                %ul.nav.nav-list
                  %li
                    - current_user.organizations.each do |org|
                      %li= link_to "#{org.name}", organization_path(org)
              - elsif (current_user.organizations.empty? && current_user.founded_orgs.empty?)
                %h4 You are not a member of any organizations, add them by editing your account in the top right

            -else
              %h3 Sign up to start chatting

    = javascript_include_tag "application"

app/views/layouts/application2.html.haml
:javascript
  window.user_email = "#{current_user.email}";
=yield